{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "helm-charts-sample.serviceAccountName" . }}
  labels:
{{ include "helm-charts-sample.labels" . | indent 4 }}
{{- end -}}
